config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'top#main'
  get 'top/main'
  resources :cartitems, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :prodducts
  has_many :cartitems
  has_many :cartitem_products, source: :product, through: :cartitems
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :product
  
  validates :product_id, :cart_id, :qty, presence: true
  validates :qty, numericality: {
      only_integer: true, 
      greater_than_or_equal_to: 1 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cartitems
  has_many :carts, source: :cart, through: :cartitems

  validates :name, :price, presence: true
  validates :price, numericality: { only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_cart
  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find(session[:cart_id])
      else
        cart = Cart.create
        session[:cart_id] = cart.id
      end
      cart
    end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def new
    @cartitem = Cartitem.new
  end
  
  def create
    @cartitem = Cartitem.new(
      product_id: params[:cartitem][:product_id],
      cart_id: current_cart.id,
      qty: params[:cartitem][:qty])
    if @cartitem.save
      flash[:notice] = 'カートに追加しました'
      redirect_to root_path
    else
      flash.now[:alert] = 'エラーがあります'
      render new_cartitem_path, status: :unprocessable_entity
    end
  end
  
  def destroy
    @cartitem = Cartitem.find(params[:id])
    if @cartitem.destroy
      flash[:notice] = 'カートから削除しました'
      redirect_to cart_path(current_cart.id)
    else
      render cart_path(current_cart.id), status: :unprocessable_entity
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitems = Cartitem.where(cart_id: current_cart.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(
      name: params[:product][:name], 
      price: params[:product][:price])
     if @product.save
       flash[:notice] = '商品を追加しました'
       redirect_to products_path
     else
       render new_product_path, status: :unprocessable_entity
     end
  end
  
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = '商品を削除しました'
      redirect_to products_path
    else
      render product_path, status: :unprocessable_entity
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<% if @cartitem.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @cartitem.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @cartitem, url: cartitems_path do |f| %>
  <p>
    <%= f.label :name, '商品名称' %>
    <%= Product.find(params[:product_id]).name %>
  </p>
  <p>
    <%= f.label :price, '商品価格' %>
    <%= Product.find(params[:product_id]).price %>
  </p>
  <p>
    <%= f.label :qty, '数量' %>
    <%= f.text_field :qty %>
  </p>
  <%= f.hidden_field :product_id, value: params[:product_id] %>
  <%= f.submit '登録する' %>
<% end %>

app/views/carts/show.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>
<br>

<% total_amount = 0 %>

<% @cartitems.each do |e| %>
商品名称：<%= Product.find(e.product_id).name %><br>
価格：<%= Product.find(e.product_id).price %><br>
数量：<%= e.qty %><br>
<%= link_to 'カートから削除', cartitem_path(e), data: { turbo_method: :delete } %>
<br>

<% total_amount += Product.find(e.product_id).price * e.qty %>
<% end %>

<br>
合計金額：<%= total_amount %>円
<br>
<%= link_to '商品一覧に戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L06</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>
<br>
<% @products.each do |e| %>
商品<%= e.id %> （<%= e.name %>、<%= e.price %>）
<%= link_to '削除', product_path(e), data: { turbo_method: :delete } %>
<%= link_to "カート追加", new_cartitem_path(product_id: e.id) %>
<br>
<% end %>

<br>
<%= link_to "商品を追加する", new_product_path %><br>

<%= link_to "カートを見る", cart_path(current_cart.id) %>

app/views/products/new.html.erb
<% if @product.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @product do |f| %>
  <p>
    <%= f.label :name, '商品名称' %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
  </p>
  
  <%= f.submit '追加する' %>
<% end %>